version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Paris"
    assignees:
      - "Yggdrasil80"
    commit-message:
      prefix: "[CI]"
      include: scope
    target-branch: "master"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: "Europe/Paris"
    assignees:
      - "Yggdrasil80"
    commit-message:
      prefix: "[Cargo]"
      include: scope
    target-branch: "master"