name: Github CI - Development

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: "Set up Rust"
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: "Get CPU cores count"
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-core-count

      - name: "Cache Cargo dependencies"
        uses: Swatinem/rust-cache@v2

      - name: "Format code"
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: "Build project with Cargo"
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release -j ${{ steps.cpu-core-count.outputs.cores }}

  docker:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: "Set up QEMU for Docker Buildx"
        uses: docker/setup-qemu-action@v2
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v2

      - name: "Get CPU cores count"
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-core-count

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build and push Docker image"
        uses: docker/build-push-action@v3.1.1
        with:
          push: true
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/yggdrasil80/doc-storage:develop
          build-args: CPU_CORES=${{ steps.cpu-core-count.outputs.cores }}
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
