name: Github CI - Development

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: "Set up Rust"
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: "Cache Cargo dependencies"
        uses: Swatinem/rust-cache@v2

      - name: "Format code"
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: "Build project with Cargo"
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: "Set up QEMU for Docker Buildx"
        uses: docker/setup-qemu-action@v2
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v2
      - name: "Login to Docker GitHub Container Registry"
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.1.1
        with:
          tags: ghcr.io/${{ github.repository }}:dev-${{ github.sha }}
          platforms:  linux/amd64,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6