name: Github CI - Development

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: "Set up Rust"
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: "Get CPU cores count"
        run: echo "CORES=$(nproc)" >> $GITHUB_ENV

      - name: "Cache Cargo dependencies"
        uses: Swatinem/rust-cache@v2

      - name: "Format code"
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: "Build project with Cargo"
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -j ${{ env.CORES }}